allow_subsequent_nan_losses: 10
batch_size: 96 # check out for single basin
clip_gradient_norm: 1
clip_targets_to_zero:
  - Qout
data_dir: ./data/CLEAR_CREEK/
dataset: generic
device: cpu
dynamic_inputs:
  - APCP_surface
  - TMP_2maboveground
epochs: 15
experiment_name: clear_creek
head: regression
hidden_size: 126
img_log_dir: ../neuralhydrology/runs/clear_creek/img_log
initial_forget_bias: 3
learning_rate:
  0: 0.001
  2: 0.0008
  4: 0.0005
log_interval: 5
log_n_figures: 1
log_tensorboard: false
loss: NSE
metrics:
  - NSE
  - KGE
model: cudalstm
number_of_basins: 1
optimizer: Adam
output_activation: linear
output_dropout: 0.4
package_version: 1.10.0
predict_last_n: 1
run_dir: ./trained_nh_models/clear_creek
save_weights_every: 1
seed: 101
seq_length: 720
static_attributes:
  - elev_mean
  - slope_mean
target_variables:
  - Qout
test_basin_file: ./data/CLEAR_CREEK/lumped_basins.txt
test_end_date: 31/12/2022
test_start_date: 11/03/2019
train_basin_file: ./data/CLEAR_CREEK/lumped_basins.txt
train_end_date: 31/12/2022
train_start_date: 01/01/2020
validate_every: 1
validate_n_random_basins: 1
validation_basin_file: ./data/CLEAR_CREEK/lumped_basins.txt
validation_end_date: 30/09/2021
validation_start_date: 10/01/2020
